[package]
name = "mal"
version = "0.1.0"
edition = "2024"

[dependencies]
winapi = { version = "0.3", features= ["memoryapi", "winnt", "processthreadsapi"]}
windows = "0.56.0"
ntapi = "0.4"
base64 = "0.21"
hex = "0.4"
web3 = "0.18.0"
tokio = { version = "1", features = ["full"]}
anyhow = "1"
